version: '3'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bookland
      POSTGRES_USER: bookland
      POSTGRES_PASSWORD: bookland
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db: